alkemyTech/OT129-CLIENT

package.json, src/App.js, src/Components/Slides/SlidesContainer.js, src/Components/Slides/SlidesItem.js, src/Components/Slides/SlidesList.js
Add Slides components Containter, List and item.
Add route /backoffice/slides in App.js file.
*
=> Ot129 64 screen listado de slides backoffice

src/Components/About/MemberCard.css, src/Components/About/MemberCard.js, src/Components/About/MembersList.js
Add component MemersList that receives an array of objects and map them.
Add component Member Card that receives an object and show data in a card presentation
=> Ot129 67 listado de miembros de la organizacion pagina nosotros

src/App.js, src/Containers/CardContainer/ContainerCard.js, src/Pages/ActivitiesPage.js
-**ActivtiesPage is created to contain and render the components referred to in the section**
-**string properties are attributed to the title component**
=> Ot129 57 componente contenedor activitiespage

src/Services/privateApiService.js
**put request created for reuse in private services**
=> OT129-71-Crear-metodo-reutilizable-PUT

src/Services/privateApiService.js
Creacion de peticion POST.
La misma chequea que haya un token en el header (funcion creada para busqueda de item en localstorage).
La peticion, valida si es con ID o no, por cuestion de que si se necesita enviar una informacion con ID (ejemplo: edicion de datos de un formulario) o en caso de que sea sin ID, envio de registro de usuario
=> Ot129 70 peticion post endpoints privados

.env.example, src/Services/ActivitiesService.js
Creada la variable de entorno en el archivo .env 
Creado un archivo .env.example con los placeholders de las variables de entorno.
Modificado el endopoint en el servicio activities.
Ticket:
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-84&quickFilter=395
Evidence:
=> [OT 129-84] crear variables de entorno (Activities)

.env.example, src/Services/TestimonialsService.js
Creacion variable entorno para Testimonials
Se realizo la creacion del del env.example con sus respectivos placeholders
Por ulitimo, se implemento la variable de entorno en el servicio requerido de Testimonials
=> Ot129 89 variables entorno testimonios

src/Containers/CardContainer/ContainerCard.js, src/Containers/CardContainer/ShowCard.css, src/Containers/CardContainer/ShowCard.js, src/Pages/NewsPage.js
GET Request in PublicApiService was created so it was added a GET Request function in News Page to test the endpoint. 
Data showing correctly in the news page:
=> [OT129 74] Desarrollar servicio y métodos reutilizables para realizar una petición GET a las rutas públicas de la API

src/Services/NewsService.js, src/Services/privateApiService.js
-**Feat: delete request in private services created**
=> OT129-73-Metodo-DELETE-endpoints-privados

README.md, package.json, src/utils/alerts.js
- title: the message to be displayed.(string)
- icon: the icon to be displayed.(string)
* "success"
* "error"
* "info"
* "warning"
* "question"
```
alerts("Confirmación de prueba", "success");
```
```
alerts("Error de prueba", "error");
```
```
alerts("Información de prueba", "info");
```
=> Ot129 95 setup alertas

README.md, src/Components/Progress/Progress.css, src/Components/Progress/Progress.js
**DESCRIPTION:**
- Created custom Progress bar component.
- Documented it's use in README.md
- Tested component
**EVIDENCE:**
=> OT129-94-Progress

README.md, package.json, src/Components/Spinner/Spinner.js
Criteria of acceptance:
Create a reusable loader spinner component,
Document your implementation in the README.md.
Bootstrap "spinners" were implemented to show the loading status in the project.
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-92&assignee=61957757977c5b00725b8e07
=> Ot129 92 create spinner

src/Containers/HomeSlide/HomeSlide.js
- added alert in the component HomeSlide
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-101
=> OT129-101-Mostrar errores cuando las peticiones no se realicen correctamente

package.json, src/App.js, src/Components/Slides/SlidesContainer.js, src/app/store.js, src/features/slides/slidesSlice.js
- The slide reducer was added to the store
- A slice of slides was added in the slides folder of the feature and the use of redux was implemented
https://alkemy-labs.atlassian.net/browse/OT129-110
=> [OT129-110] crear reducer de slides

src/Components/StatusHandler/StatusHandler.js, src/Containers/HomeSlide/HomeSlidesContainer.js, src/Containers/NewsCards/NewsCards.js, src/Pages/NewsPage.js, src/constants/index.js, src/features/Members/membersSlice.js, src/features/News/news-slice.js, src/features/Organization/organizationSlice.js, src/features/slides/slidesSlice.js
**DESCRIPTION:**
- Created new file with status const for common use in slicers.
- Imported const in current slices
- Updated services with redux
- Added status handler to services.
**EVIDENCE:**
=> Redux status file

src/App.js, src/Components/Header/Header.css, src/Components/Header/Header.js, src/index.css
HOW: User
I WANT: Display a header on the public web
FOR: Being able to navigate through the different sections
THE FIGMA DESIGN WAS FOLLOWED
Some links were left public (without the need for the user to be logged in)
The links of the "Campaigns" are shown only if the user is logged in.
* The routes of LoginForm and RegisterForm are not yet active in App.js
*<Header/> just for review it was incorporated into the App.js route
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-124&assignee=61957757977c5b00725b8e07
=> [OT129-124] componente header

src/Campaigns/School/Footer.js, src/Campaigns/School/styles.css
- A footer component was created for school campaigns implementing mobile first
https://alkemy-labs.atlassian.net/browse/OT129-133
Mobile
Tablet
PC
SmartTv
=> [OT129-133] Estructurar componente Footer campaña escuelas

src/Campaigns/Toys/Slider.js, src/Campaigns/Toys/slider.module.css
- Created slide component for toys campaign.
- Slide changes image at 5 seconds.
- In phones and tablet views don't show the text caption.
Ticket:
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-138&quickFilter=395
Evidence:
- Mobile and tablets
- Desktop and +
=> [Ot129 138] Estructurar componente slider

src/App.js, src/Components/Layout/LayoutPublic.js
-LayoutPublic.js: create Layout component & integrate header and footer.
- ### Home.
- ### About.
=> feat: create layout component

src/Components/BackNavBar/BackNavBar.css, src/Components/BackNavBar/BackNavBar.js, src/Containers/Backoffice/BackCards.css, src/Containers/Backoffice/BackCards.js, src/Containers/Backoffice/Backoffice.js, src/Containers/Backoffice/backoffice.css
=> Refactor Backoffice Home

src/Components/Header/Header.js, src/features/auth/authSlice.js
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-140
Acceptance criteria: The session will be closed from the client, eliminating all user data from localStorage. Also, ensure that the Log Out button is shown only when the user is authenticated
=> [OT129-140] Crear lógica de cierre de sesión

README.md, src/Components/SearchInput/SearchInput.js, src/Components/SearchInput/searchInput.md, src/Containers/Activities/ActivitiesListContainer.js, src/Services/ActivitiesService.js, src/Services/publicApiService.js, src/features/Activities/activitiesSlice.js, src/hooks/useDebouceSearch.js, src/hooks/useDebounceSearch.md
**DESCRIPTION:**
- Created a new component for handling activities searching.
- Created a custom hook for handling debounce effect when searching an activity.
- Documented both uses.
**EVICENCE:**
**PR:**
- https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-166
=> Ot129 166 search actividades

src/Components/News/NewsList.jsx, src/Components/SearchInput/SearchInput.js, src/Services/NewsService.js, src/features/News/news-slice.js
- NewsService.js
- Add search argument with null default value. (commit: https://github.com/alkemyTech/OT129-CLIENT/commit/472fc26e2988f04b7417f90cc6ebdd6ffb71d8a1)
- news-slice.js
- Add search argument in get News. (commit: https://github.com/alkemyTech/OT129-CLIENT/commit/2697a56490d59e5440891cd043e8c23a561358ef)
- SearchInput.js
- Add margin bottom. (commit: https://github.com/alkemyTech/OT129-CLIENT/commit/1a395bb4b260b33314362d30b9ee988781cbb377)
- NewsList.jsx 
- Add search service with debounce effect. It use the UseDebounceSearch custom hook. (commit: https://github.com/alkemyTech/OT129-CLIENT/commit/a3b50a13eac7aa8a4d6bb6703e1a9e25b13b457a)
- ### Search bar.
- ### Search not found.
- ### Search success.
=> [Ot129-165] Crear formulario de busqueda de novedades

src/Components/Auth/RegisterForm.js
-**auth reducer is imported**, 
-**Is redirected to the home page if the user is logged in**(https://github.com/alkemyTech/OT129-CLIENT/commit/6b2a4affa02cb8629a6a425850b06b32978efb29)
=> [Ot129-143] Restringir acceso a Formulario de registro

src/Components/Auth/LoginForm.js, src/Components/Auth/RegisterForm.css, src/Components/Auth/RegisterForm.js, src/Components/News/NewsList.jsx, src/Containers/Categories/CategoriesListContainer.js, src/Pages/LoginPage.js, src/hooks/useDebounceSearch.md
**SUMMARY:**
- Fixed useDebounceSearch imports due file rename
- Fixed Login redirection that wasn't working properly (the right redirection was inside the onSubmit function and the page was forcing another one by history.push). Added styles.
- Uncommented lines in the register handleSubmit.
=> HOTFIX: Login and useDebounceSearch

src/Components/Header/Header.js, src/Components/Header/Header.module.css, src/Components/Header/MobileNav.jsx, src/Components/Header/MobileNav.module.css, src/Components/Popups/RegisterPopup.css, src/constants/index.js, src/index.css
**SUMMARY:**
- Created new MobileNav component and styles for mobile breakpoint up to 1023px.
- Updated existent styles for common use.
**EVIDENCE:**
**ISSUE:**
https://github.com/alkemyTech/OT129-CLIENT/issues/162
=> FEAT: Mobile Menu
